# Generated by Django 6.1.2 on 2026-10-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref_No', models.IntegerField()),
                ('Name', models.CharField(max_length=10)),
                ('Dob', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Percent', models.FloatField()),
                ('Address', models.TextField()),
                ('Hobbies', models.CharField(max_length=20)),
            ],
        ),
    ]
