# Generated by Django 6.1.2 on 2026-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vechicle_dB',
            fields=[
                ('license_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('faults_found', models.TextField()),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_contact', models.IntegerField()),
                ('owner_address', models.TextField()),
                ('deposit_payed', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='student_DB',
        ),
    ]
